services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    expose:
      - 8080
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - SITE_OWNER=${SITE_OWNER}
      - APP_KEY=${APP_KEY}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE}
      - TZ=${TZ}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - APP_LOG_LEVEL=${APP_LOG_LEVEL}
      - AUDIT_LOG_LEVEL=${AUDIT_LOG_LEVEL}
      - AUDIT_LOG_CHANNEL=${AUDIT_LOG_CHANNEL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CACHE_DRIVER=${CACHE_DRIVER}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - REDIS_SCHEME=${REDIS_SCHEME}
      - REDIS_PATH=${REDIS_PATH}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_CACHE_DB=${REDIS_CACHE_DB}
      - COOKIE_PATH=${COOKIE_PATH}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - COOKIE_SECURE=${COOKIE_SECURE}
      - COOKIE_SAMESITE=${COOKIE_SAMESITE}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - SEND_ERROR_MESSAGE=${SEND_ERROR_MESSAGE}
      - SEND_REPORT_JOURNALS=${SEND_REPORT_JOURNALS}
      - ENABLE_EXTERNAL_MAP=${ENABLE_EXTERNAL_MAP}
      - ENABLE_EXCHANGE_RATES=${ENABLE_EXCHANGE_RATES}
      - ENABLE_EXTERNAL_RATES=${ENABLE_EXTERNAL_RATES}
      - MAP_DEFAULT_LAT=${MAP_DEFAULT_LAT}
      - MAP_DEFAULT_LONG=${MAP_DEFAULT_LONG}
      - MAP_DEFAULT_ZOOM=${MAP_DEFAULT_ZOOM}
      - AUTHENTICATION_GUARD=${AUTHENTICATION_GUARD}
      - AUTHENTICATION_GUARD_HEADER=${AUTHENTICATION_GUARD_HEADER}
      - AUTHENTICATION_GUARD_EMAIL=${AUTHENTICATION_GUARD_EMAIL}
      - CUSTOM_LOGOUT_URL=${CUSTOM_LOGOUT_URL}
      - DISABLE_FRAME_HEADER=${DISABLE_FRAME_HEADER}
      - DISABLE_CSP_HEADER=${DISABLE_CSP_HEADER}
      - ALLOW_WEBHOOKS=${ALLOW_WEBHOOKS}
      - STATIC_CRON_TOKEN=${STATIC_CRON_TOKEN}
      - APP_URL=${APP_URL}
      - USE_RUNNING_BALANCE=${USE_RUNNING_BALANCE}
      - FIREFLY_III_LAYOUT=${FIREFLY_III_LAYOUT}
    depends_on:
      - db
  db:
    image: docker.io/library/postgres:18-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - firefly_iii_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    expose:
      - 5432
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    environment:
      - TZ=${TZ}
      - STATIC_CRON_TOKEN=${STATIC_CRON_TOKEN}
    command: sh -c "
      apk add tzdata && \
      (ln -s /usr/share/zoneinfo/$$TZ /etc/localtime || true) && \
      echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\"
      | crontab - && \
      crond -f -L /dev/stdout"
    depends_on:
      - app

volumes:
   firefly_iii_upload:
   firefly_iii_db:
