cloudflare:
  tunnelName: k8s-wittnerlab
  tunnelId: f9de1d0c-0f6f-4389-b8cb-029bee73d70d
  secretName: cloudflare-tunnel-secret
  ingress:
    - hostname: "*.wittnerlab.com"
      service: "https://traefik.traefik.svc.cluster.local:443"
      originRequest:
        noTLSVerify: true
image:
  repository: cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: 2025.11.1
resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
replicaCount: 2
