services:
  kuma:
    image: louislam/uptime-kuma:2.0.2
    restart: unless-stopped
    volumes:
      - ../files/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 3001