apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    example: basic
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: 36.3.0
      chart: traefik
      helm:
        valueFiles:
          - $infra-repo/k8s_gitops/cluster_talos_ovh/infra/traefik/resources/values.yaml
      # Source pour les ressources auxiliaires (namespace, secrets, etc.)
    - repoURL: https://github.com/jbwittner/infrastructure
      targetRevision: main
      ref: infra-repo
      path: k8s_gitops/cluster_talos_ovh/infra/traefik/resources
