---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn/longhorn.yaml
  - traefik/traefik.yaml
  - sealed-secrets/sealed-secrets.yaml
  - external-dns/external-dns.yaml
  - cloudflare-tunnel